source "http://rubygems.org"

#gem "rack", "1.4.1" 
#gem "rack", "1.4.1",  :git =>  "git://github.com/rack/rack.git" 
gem "sinatra", :require => "sinatra/base"
gem "sinatra-reloader"
gem "capistrano"
gem "capistrano-ext"

#gem "shotgun"
gem "haml"
gem "json"
gem "datamapper"
gem "dm-migrations"
gem "dm-transactions"
gem "dm-sqlite-adapter"
gem "dm-mysql-adapter"
gem "dm-aggregates"
gem "dm-types"
gem "inifile" #, "~> 0.3"
gem "extlib"
gem "rdebug"
gem "thin"
gem "unicorn"
