source "http://rubygems.org"

gem "rack", "~> 1.3"
gem "sinatra", :require => "sinatra/base"
gem "sinatra-reloader"
gem "shotgun"
gem "haml"
gem "json"
gem "datamapper"
gem "dm-migrations"
gem "dm-transactions"
gem "dm-sqlite-adapter"
gem "dm-mysql-adapter"
gem "dm-aggregates"
gem "inifile", "~> 0.3"
gem "extlib"
